### PR TITLE
TFGridNet Integration #109

### PR DESCRIPTION
**Pull request by pradumna-gautam**
**What does this PR do? Please describe:**
Integrates TFGridNet from ESPNET into fairseq2. 

Fixes #{109}

**Does your PR introduce any breaking changes?
No

**Check list:**
- [x] Was the content of this PR **discussed and approved** via a GitHub issue? (no need for typos or documentation improvements)
- [x] Did you read the [contributor guideline](https://github.com/facebookresearch/fairseq2/blob/main/CONTRIBUTING.md)?
- [x] Did you make sure that your **PR does only one thing** instead of bundling different changes together?
- [x] Did you make sure to **update the documentation** with your changes? (if necessary)
- [x] Did you write any **new necessary tests**?
- [x] Did you verify new and **existing tests pass** locally with your changes?
- [x] Did you **update the [CHANGELOG](https://github.com/facebookresearch/fairseq2/blob/main/CHANGELOG.md)**? (no need for typos, documentation, or minor internal changes)

### CODE REVIEW

**Comment by pradumna-gautam** [comment]
Testing the TFGridNet Toolkit locally:

1. You need to install additional dependencies in order to run tfgridnet:

    pip install typeguard==2.13.3
    pip install torch-complex

2. In tfgridnet_test.py, update paths for input audio, config (.yaml), model (.pth), and output.

3. Run tfgridnet_test.py to produce enhanced_audio.wav.

**Comment by pradumna-gautam** [comment]
Testing the denoise_and_vad_audio.py locally. 

- denoise_and_vad_audio.py is taken from fairseq, which uses a pre-trained master64 model for speech enhancement in the "--denoise" part. 

- In this PR, I have included an additional model called SeperateSpeech (TFGridnet tool) from ESPNet repository. 

- Now this updated denoise_and_vad_audio toolkit takes both SperateSpeech and master64(default) models. Based on the given argument (--model SeperateSpeech) it uses the SeperateSpeech model instead of master64.

- **Note:** This script is tested on an individual audio file: .wav file and not on the .tsv file. (For testing purposes)
- Please replace the path for input.wav in denoise_and_vad_audio.py, 
- Replace path for config.yaml, and model.pth file in SeperateSpeech model (denoise_and_vad_audio.py)
- 
- **How to Test:**
Locally, just run the following: 

1) To test master64:

python denoise_and_vad_audio.py --audio-input $AUDIO_FILE --output-dir $OUTPUT_DIR --denoise --vad

2) To test SeperateSpeech:

python denoise_and_vad_audio.py --audio-input $AUDIO_FILE --output-dir $OUTPUT_DIR  --model SeperateSpeech --denoise --vad


It will generate two output audios: denoise and vad audio files in their respective directory.

**Comment by pradumna-gautam** [comment]
To test the updated denoise_and_vad_audio.py locally.

Note: This script is tested on an .tsv file (as per original fairseq). 
.tsv file contains filename/path for the audio stored the local.

- This updated code deals with additional arguments for SeperateSpeech i.e. --config : configuration.yaml file and --pth-model : path for the model .pth file.

How to Test:
Locally, just run the following:

To test master64:
python denoise_and_vad_audio.py --audio-manifest $INPUT_MANIFEST --output-dir $OUTPUT_DIR --denoise --vad

($INPUT_MANIFEST is path for .tsv file)

To test SeperateSpeech:
python denoise_and_vad_audio.py --audio-manifest $INPUT_MANIFEST --output-dir $OUTPUT_DIR --model SeperateSpeech --config /path/to/config.yaml --pth-model /path/to/model.pth --denoise --vad

It will generate two output audios: denoise and vad audio files in their respective directory.

**Comment by cbalioglu** [comment]
Since this PR is pretty much a literal copy/paste of TFGridNet from espnet with zero integration with the rest of the fairseq2, I  suggest putting it into its own repository. TBH I see no purpose/benefit for having this work in fairseq2.

**Comment by cbalioglu** [comment]
Assuming this has been now moved to fairseq or to an internal repo with the end of the MLH program.

**Pull request closed without merging**
